// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-SNssXT-lSvBVVR9VOZwVerWggNbePY',
    appId: '1:72336069732:web:28c4de8b957fabb8e6fb71',
    messagingSenderId: '72336069732',
    projectId: 'useronlineorder-c620f',
    authDomain: 'useronlineorder-c620f.firebaseapp.com',
    storageBucket: 'useronlineorder-c620f.appspot.com',
    measurementId: 'G-5KTTEELQD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLkjocq-a8u9vKUWjYAW3SHDTzXyjU7w',
    appId: '1:72336069732:android:8bcbfbcfbbbd57e5e6fb71',
    messagingSenderId: '72336069732',
    projectId: 'useronlineorder-c620f',
    storageBucket: 'useronlineorder-c620f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHQhAac7O7MQf7BbBUpryvfctfYJH77M',
    appId: '1:72336069732:ios:ac1e32b92752ebe2e6fb71',
    messagingSenderId: '72336069732',
    projectId: 'useronlineorder-c620f',
    storageBucket: 'useronlineorder-c620f.appspot.com',
    iosBundleId: 'com.adnanturgay.usersapp',
  );
}
